### ISSUE TITLE
Make bots immune from spawnkill_autokick

### ISSUE THREAD

**Issue by ge0rdie** [SpunkyBot/spunkybot#55]
It looks like bots can be auto kicked for spawn killing.   This can result in unbalanced teams when all humans have left the server.

Requesting that bots be made immune from this the same way admins are.

I have made the following small change to see if it fixes the problem, but I am not a Python programmer and I have only guessed how to identify a player as a bot:
```
# spawn kill warning
if self.spawnkill_autokick and killer.get_admin_role() < 40 and killer.get_ip_address() != 'bot':
```

**Comment by alexanderkress** [comment]
You are right, it is possible to identify bots (with a small different approach).
However, since I saw your request in your forum, I was already working a solution and I took over some of your ideas:
- spawnkilling bots will be killed and never warned
- there will be a new option, that the operator can choose to kill spawn killers or to warn/kick them. also the combination of both options is possible

Additionally, low score warning and TKs will also not lead to warnings of bots to avoid unbalanced teams.
