### ISSUE TITLE
Doesn't show all maps

### ISSUE THREAD

**Issue by that0n3guy** [SpunkyBot/spunkybot#56]
We use docker and store our maps (with a docker volume) in the `q3urt4/downloads` folder (it makes adding maps very quick and easy).

I'm having an odd issue where spunky doesn't see many maps... or will see them sometimes, but not always.

Here is the issue:

* When I first reboot spunky server and type `!maps`, I see most of the maps (still, not all of them).   Then I choose a non-standard map like `!map library` (for example its located in `q3urt4/downloads`).
* after library has loaded, If I immediately type `!maps`  again, I will only see about half the maps, all the default ones and a couple that are located in the `q3urt4/downloads` folder. (Sometimes... but not always... if I wait between bullet 1 and 2 above, I'll get a list of maps like I did originally... but not often).
* if I type the exact same command `!map library` as I did 1 minute before, it will tell me "map not found".    

There are certain maps that spunky will never see... but I can vote for them or rcon change to them.

Can you help me with this?   Thanks!

**Comment by alexanderkress** [comment]
How many custom maps are located in your downloads folder?
Which version of UrT are you using?

Could you please check the following command ingame:
- load your library map
- afterwards open console and enter: /rcon dir map bsp
- check which maps are listed
- also enter the following console command:  /rcon fdir *.pk3
- check which maps are listed

I assume that the rcon feedback does not list all maps, or even that one of the above mentioned commands is empty (output " " or "[ ]" ).

**Comment by alexanderkress** [comment]
could you also check in your spunkybot folder the file called `devel.log`? There should be an error message after the `!maps` command was not able to show all maps.

**Comment by that0n3guy** [comment]
On the server, by running `ls /q3urt/*.pk3 -l` I have the 23 default maps , 100 custom maps (running `ls download/*.pk3 -l`).

Here are some console dumps:

1.  `!maps` after fresh splunkybot server reboot (just for reference): 
[consoledumpmaps.txt](https://github.com/SpunkyBot/spunkybot/files/2155967/consoledumpmaps.txt)
1.  after switching to library map.  I ran `!maps` and `/rcon dir map bsp`:
[consoledumplibrary.txt](https://github.com/SpunkyBot/spunkybot/files/2155970/consoledumplibrary.txt)
1. running `/rconf dir *.pk3` (it might not be showing the whole list)
[consoledumplibrary2.txt](https://github.com/SpunkyBot/spunkybot/files/2155974/consoledumplibrary2.txt) This one is weird to me... Maybe I don't understand the command, but it maps listed twice (example `/ut4_suburbia_b9.pk3` through `/wop_diner_b4.pk3`)... the first time being in the q3ut4 folder on the server... which it is not.  Here is proof:
```
root@18e186ade3c7:/home/urt/UrbanTerror43/q3ut4# ls
autoexec_example.cfg           server_example.cfg  zUrT43_004.pk3  zUrT43_009.pk3  zUrT43_014.pk3  zUrT43_019.pk3
download                       ut4_jumpents.pk3    zUrT43_005.pk3  zUrT43_010.pk3  zUrT43_015.pk3  zUrT43_020.pk3
mapcycle_example.txt           zUrT43_001.pk3      zUrT43_006.pk3  zUrT43_011.pk3  zUrT43_016.pk3  zUrT43_021.pk3
QIIIA_Game_Source_License.doc  zUrT43_002.pk3      zUrT43_007.pk3  zUrT43_012.pk3  zUrT43_017.pk3  zUrT43_qvm.pk3
readme43.txt                   zUrT43_003.pk3      zUrT43_008.pk3  zUrT43_013.pk3  zUrT43_018.pk3
root@18e186ade3c7:/home/urt/UrbanTerror43/q3ut4#
```

Counts from my results:

- `!maps` bullet 1 shows 101 maps
- `!maps` bullet 2 above is 51 maps
- `/rcon dir map bsp` from bullet 2 shows 134 maps
- `/rcon fdir *.pk3` from bullet number 3, if you don't count the duplicates, it shows 123 maps

> could you also check in your spunkybot folder the file called devel.log? There should be an error message after the !maps command was not able to show all maps.

I don't see a debug.log file anywhere:
```
root@58266717002d:/opt/spunkybot# ls
CHANGELOG.md        CONTRIBUTING.md     doc      MANIFEST.in  setup.cfg  sqlite                     wait-for-30sec.sh
CODE_OF_CONDUCT.md  debian              lib      README.md    setup.py   systemd-spunkybot.service
conf                debian-startscript  LICENSE  SECURITY.md  spunky.py  VERSION
root@58266717002d:/opt/spunkybot# find -O3 -L ./ -name "debug.log"
```

### Other info:
Two example maps that spunkybot never see's are `ut4_cache_b6` and `ut4_blitzkrieg2`

**Comment by alexanderkress** [comment]
Yes, this is Urban Terror... Even the game itself is not able to count the loaded maps....
Due to that I have to use two different commands to get some maps and afterwards remove all the redundant maps.

This high amount of maps is indeed a problem for UrT.
The bot can just use the commands which are supported by the game. And since even these commands do not provide real values, I am lost.

So after a mapcycle only 51 maps are listed?
When restarting the bot, 101 maps are listed?

So this means after a mapcycle, RCON is not given proper results.

Which server hardware are you using?
Maybe the bot needs to wait a bit longer, since the mapcycle is using too much resources.

The file is called devel.log, not debug...
Since your listing is also not showing the data.sqlite or spunky.pyc files, you must have a different folder for the runtime files...

**Comment by alexanderkress** [comment]
So I was able to find a bug in the code. The maximum number of maps is currently limited to 54 maps, since the RCON feedback is not giving all maps at a time.
I am now trying to gather all the feedback in a while loop. I am testing with 104 maps, now the result is reliable. Currently I am investigating if the fdir *.bsp command or the dir map bsp command is better.
ut4_cache_b6 is also showing with my bugfix.
Will be included in the next release.

**Comment by that0n3guy** [comment]
Nice, thanks!
